import { AccountIcon } from "./AccountIcon";
import { AddCardIcon } from "./AddCardIcon";
import { AddIcon } from "./AddIcon";
import { ArrowBackIcon } from "./ArrowBackIcon";
import { BackspaceIcon } from "./BackspaceIcon";
import { BookIcon } from "./BookIcon";
import { CheckCircleIcon } from "./CheckCircleIcon";
import { CloseIcon } from "./CloseIcon";
import { CreditCardIcon } from "./CreditCardIcon";
import { DashboardIcon } from "./DashboardIcon";
import { DeleteIcon } from "./DeleteIcon";
import { DocIcon } from "./DocIcon";
import { EditIcon } from "./Editcon";
import { ErrorIcon } from "./ErrorIcon";
import { LoadingIcon } from "./LoadingIcon";
import { LoginIcon } from "./LoginIcon";
import { MastercardIcon } from "./MastercardIcon";
import { PostAddIcon } from "./PostAddIcon";
import { RupayIcon } from "./RupayIcon";
import { SwapIcon } from "./SwapIcon";
import { SyncIcon } from "./SyncIcon";
import { TransactionIcon } from "./TransactionIcon";
import { VisaIcon } from "./VisaIcon";
import { VisibilityIcon } from "./VisibilityIcon";
import { VisibilityOffIcon } from "./VisibiltyOffIcon";

export { AccountIcon, AddCardIcon, AddIcon, ArrowBackIcon, BackspaceIcon, BookIcon, CheckCircleIcon, CloseIcon, CreditCardIcon, DashboardIcon, DeleteIcon, DocIcon, EditIcon, ErrorIcon, LoadingIcon, LoginIcon, MastercardIcon, PostAddIcon, RupayIcon, SwapIcon, SyncIcon, TransactionIcon, VisaIcon, VisibilityOffIcon, VisibilityIcon };